version: "3"

services: 
  backend:
    container_name: backend_container
    build:
      context: ../packages/backend/.
      dockerfile: Dockerfile
    volumes:
      - ../packages/backend:/backend/
      - static_volume:/backend/staticfiles
    stdin_open: true
    tty: true
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      - backend_network
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
volumes:
  static_volume:
