name: GitHub Actions
on: [pull_request]
jobs:
  test:
    name: unit test for backend
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: .github/docker-compose-ci.yml
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - name: Build docker images
        run: docker-compose -f $COMPOSE_FILE build
      - name: Run tests
        run: make test-backend-ci
